# local costmap is not static
rolling_window: true

# publish rate
publish_frequency: 5.0



robot_base_frame: chassis
static_map: true

obstacle_range: 30.0
raytrace_range: 3.0

robot_radius: 0.0
inflation_radius: 0.3


observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: laser_scanner2, data_type: LaserScan, topic: /ourscan, marking: true, clearing: true}
